### ISSUE TITLE
Is it possible to run this locally (without google cloud)?

### ISSUE THREAD

**Issue by sxiii** [Courtsite/shuttlepdf#1]
Hi @MrSaints ! Sorry for much disturbing ;) 

I would like to run this code on my own server without google. Is that possible?

And, additional question. I am also trying to build it statically with [static-link](https://github.com/fearthecowboy/static-link), here is my slightly changed package.json:
<details>
  <summary>Code</summary>
<code>
{
  "name": "shuttlepdf",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "https://github.com/courtsite/shuttlepdf",
  "author": "Courtsite <tech@courtsite.my>",
  "license": "MIT",
  "dependencies": {
    "puppeteer": "^1.11.0",
    "electron": "^3.1.13"
  },
  "devDependencies": {
    "prettier": "^1.15.3",
    "electron-packager": "^12.1.0",
    "static-link": "*"
  },
  "scripts": {
    "fmt": "prettier --write *.js",
    "clean": "rm -rf build/",
    "build:prepare": "mkdir -p build/ && cp index.js build/ && cp package.json build/ && cd build/ && npm i --production",
    "build:linux": "electron-packager build/ shuttlepdf --platform=linux --arch=x64 --electron-version=3.1.13 --out=build/ --overwrite --no-prune",
    "build": "npm run clean && npm run build:prepare && npm run build:linux",
    "static-link": "static-link --force"
  },
  "static-link": {
    "dependencies": {
      "chalk": "*",
      "marked": "*",
      "marked-terminal": "*",
      "yarn": "^1.1.0",
      "commander": "^2.9.0",
      "electron": "3.1.13",
      "rw": "^1.3.2"
    }
  }
}
</code>
</details>

I can't get that to work. But first important is the main issue with google cloud of course or how to run locally...

**Comment by MrSaints** [comment]
Not at the moment unfortunately. But it should be easy to pull the code out, and fit it to your needs 😄
